
struct MENUTEXTS menudata[] =
{
	"STARTMENUSYSTEM",
/************************************************/
/*   Dansk                                      */
/************************************************/
		"LAN",
/* hovedmenu */
			"MENU",
				"Kugle Labyrint",
				"Hovedmenu",
				"Ramme",
				"Rute",
				"Huller",
				"Juster labyrint",
				"Start labyrint",
				"Parametre",
				"Hj\33lp",
				"Afslut program",
			"ENDMENU",
/* ramme menu */
			"MENU",
				"Ramme Menu",
				"",
				"Find ramme",
				"Klik ramme",
				"Slut",
			"ENDMENU",
/* rute menu */
			"MENU",
				"Rute Menu",
				"",
				"Klik rute",
				"L\33s rute fra disk",
				"Skriv rute p\35 disk",
				"Punkt \33ndres",
				"Nyt punkt",
				"Slut",
			"ENDMENU",
/* rute input menu */
			"MENU",
				"L\33s rute fra disk",
				"",
				"Standard rute",
				"Anden rute",
				"Slut",
			"ENDMENU",
/* hul menu */
			"MENU",
				"Hul Menu",
				"",
				"Klik huller",
				"L\33s huller fra disk",
				"Skriv huller p\35 disk",
				"Slut",
			"ENDMENU",
/* hul input menu */
			"MENU",
				"L\33s huller fra disk",
				"",
				"Standard huller",
				"Andre huller",
				"Slut",
			"ENDMENU",
/* parameter menu */
			"MENU",
				"Parameter Menu",
				"",
				"Nye parametre",
				"Setup",
				"Sprog",
				"Slut",
			"ENDMENU",
/* ny parameter menu */
			"MENU",
				"Nye parametre",
				"",
				"Hastighed",
				"LP-filter tidskonst.",
				"Maksimal afvigelse",
				"Antal fejl-billeder",
				"Standardparametre",
				"Slut",
			"ENDMENU",
/* setup menu */
			"MENU",
				"Setup",
				"",
				"Scan/Sync kanal",
				"Kamera",
				"Standard setup",
				"Slut",
			"ENDMENU",
/* sprog menu */
			"MENU",
				"Skift Sprog",
				"",
				"Engelsk",
				"Dansk",
				"Tjekkisk",
				"Slut",
			"ENDMENU",
/* kamera menu */
			"MENU",
				"Kamera setup",
				"",
				"SL429C",
				"SL429D",
				"SL429E",
				"SL447",
				"Andet kamera",
				"Slut",
			"ENDMENU",
			/*  Start menu  */
			"MENU",
				"Start menu",
				"",
				"Standard labyrint",
				"Anden labyrint",
				"Start labyrint",
				"Slut",
			"ENDMENU",
		"ENDLAN",
/************************************************/
/*   English                                    */
/************************************************/
		"LAN",
/* main menu */
			"MENU",
				"Labyrinth Game",
				"Main menu",
				"Frame",
				"Track",
				"Holes",
				"Adjust labyrinth",
				"Start labyrinth",
				"Parametres",
				"Help",
				"Terminate program",
			"ENDMENU",
/* frame menu */
			"MENU",
				"Frame Menu",
				"",
				"Detect frame",
				"Click frame",
				"Quit",
			"ENDMENU",
/* track menu */
			"MENU",
				"Track Menu",
				"",
				"Click track",
				"Read track from disk",
				"Write track to disk",
				"Change point",
				"New point",
				"Quit",
			"ENDMENU",
/* track input menu */
			"MENU",
				"Read track from disk",
				"",
				"Standard track",
				"Other track",
				"Quit",
			"ENDMENU",
/* hole menu */
			"MENU",
				"Hole Menu",
				"",
				"Click holes",
				"Read holes from disk",
				"Write holes to disk",
				"Quit",
			"ENDMENU",
/* hole input menu */
			"MENU",
				"Read holes from disk",
				"",
				"Standard holes",
				"Other holes",
				"Quit",
			"ENDMENU",
/* parameter menu */
			"MENU",
				"Parameter Menu",
				"",
				"New parameters",
				"Setup",
				"Language",
				"Quit",
			"ENDMENU",
/* new parameters menu */
			"MENU",
				"New parameters",
				"",
				"Velocity",
				"LP-filter constant",
				"Maximum deviation",
				"No. of fail-images",
				"Standard parametres",
				"Quit",
			"ENDMENU",
/* setup menu */
			"MENU",
				"Setup",
				"",
				"Scan/Sync chanal",
				"Camera",
				"Standard setup",
				"Quit",
			"ENDMENU",
/* language menu */
			"MENU",
				"Change language",
				"",
				"English",
				"Danish",
	    "Czech",
				"Quit",
			"ENDMENU",
/* camera menu */
			"MENU",
				"Camera setup",
				"",
				"SL429C",
				"SL429D",
				"SL429E",
				"SL447",
				"Other camera",
				"Quit",
			"ENDMENU",
			/*  Start menu  */
			"MENU",
				"Start menu",
				"",
				"Standard labyrinth",
				"Other labyrinth",
				"Start labyrinth",
				"Quit",
			"ENDMENU",
		"ENDLAN",

/************************************************/
/*   Cesky                                      */
/************************************************/
		"LAN",
/* hlavni menu */
			"MENU",
				"Kulicka v bludisti",
				"Hlavni menu",
				"Ram",
				"Draha",
				"Rozlozeni otvoru",
				"Umisteni bludiste",
				"Zacatek hry",
				"Parametry",
				"Napoveda",
				"Ukonci program",
			"ENDMENU",
/*  menu ram */
			"MENU",
				"Menu ram",
				"",
				"Najdi ram",
				"Rucne nastav",
				"Zpet",
			"ENDMENU",
/* menu draha */
			"MENU",
				"Menu draha",
				"",
				"Rucne nastav drahu",
				"Nacti drahu z disku",
				"Zapis drahu na disk",
				"Zmen polohu bodu",
				"Novy bod",
				"Zpet",
			"ENDMENU",
/*  menu nacteni drahy z disku*/
			"MENU",
				"Nacti drahu z disku",
				"",
				"Standartni draha",
				"Jina draha",
				"Zpet",
			"ENDMENU",
/* menu rozlozeni otvoru*/
			"MENU",
				"Menu rozlozeni otvoru",
				"",
				"Rucne nastav rozlozeni",
				"Nacti z disku",
				"Zapis na disk",
				"Zpet",
			"ENDMENU",
/*nacteni rozlozeni otvoru */
			"MENU",
				"Nacti rozloz. z disku",
				"",
				"Standartni rozlozeni",
				"Jine rozlozeni",
				"Zpet",
			"ENDMENU",
/* menu parametry */
			"MENU",
				"Menu parametry",
				"",
				"Nove parametry",
				"Nastaveni",
				"Jazyk",
				"Zpet",
			"ENDMENU",
/* new parameters menu */
			"MENU",
				"Nove  parametry",
				"",
				"Rychlost",
				"konstanta LP-filtru",
				"Maximalni odchylka",
				"Pocet 'fail-images'",
				"Standartni parametry",
				"Zpet",
			"ENDMENU",
/* menu nastaveni*/
			"MENU",
				"Nastaveni",
				"",
				"Scan/Sync kanal",
				"Kamera",
				"Standartni nastaveni",
				"Zpet",
			"ENDMENU",
/* menu jazyk*/
			"MENU",
				"Zmen jazyk",
				"",
				"Anglicky",
				"Dansky",
	    "Cesky",
				"Zpet",
			"ENDMENU",
/* menu kamera */
			"MENU",
				"Nastaveni kamery",
				"",
				"SL429C",
				"SL429D",
				"SL429E",
				"SL447",
				"Jina kamera",
				"Zpet",
			"ENDMENU",
			/*  Start menu  */
			"MENU",
				"Zacni hru",
				"",
				"Standartni bludiste",
				"Jine bludiste",
				"Zacni hru",
				"Zpet",
			"ENDMENU",
		"ENDLAN",

	"ENDMENUSYSTEM"
};

#define no_of_lans 3
#define no_of_menus 12
