######################################################################
#
# Makefile for Robot Manager Resource
#
# $Id: Makefile 11 2008-12-12 13:12:46Z s021786 $

######################################################################

#Destination directories
BINDIR := ../../bin
DOCDIR := doc

install: 
	@echo -n "   * Copying Rule resource files.. "
	@mkdir -p $(BINDIR)
	@cp  ./* $(BINDIR)
	@echo "Done"

	
#Phony targets
.PHONY: install