######################################################################
#
# Makefile for Robot Manager Resource
#
# $Id: Makefile 141 2008-05-18 15:36:24Z andersbeck $

######################################################################

#Destination directories
BINDIR := ../../bin
DOCDIR := doc

install: 
	@echo -n "   * Copying binary resource files.. "
	@mkdir -p $(BINDIR)
	@cp * $(BINDIR)
	@echo "Done"

	
#Phony targets
.PHONY: install