/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ModulePluginJPanelTemplate.java
 *
 * Created on 28-10-2009, 21:53:05
 */
package marg;

import marg.gui.plugin.*;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.JPanel;
import marg.handlers.XMLClientHandler;
import marg.model.ModuleVariable;
import marg.model.plugin.VarDataPlugin;

/**
 *
 * @author Daniel
 */
public class ModulePluginJPanelTemplate extends javax.swing.JPanel implements ModulePlugin, PropertyChangeListener {

    private XMLClientHandler clientHandler;

    /** Creates new form ModulePluginJPanelTemplate */
    public ModulePluginJPanelTemplate() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText("Design the visual representation of your plugin here");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(275, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    //This will always be called before startPlugin()
    public void setXMLClientHandler(XMLClientHandler handler) {
        this.clientHandler = handler;
    }

    public String getPluginName() {
        return "Template";
    }

    public JPanel getJPanel() {
        return this;
    }

    public void startPlugin() {
        //Initialize needed ressources
        //Handler usage example:
        clientHandler.addPropertiesChangeListener(this, VarDataPlugin.SUBSCRIBE_VARDATA);
    }

    public void stopPlugin() {
        //Close down ressources
    }

    public void doUpdate() {
        //Update some content
    }

    public void propertyChange(PropertyChangeEvent evt) {
        if (evt.getPropertyName().equals(VarDataPlugin.SUBSCRIBE_VARDATA)) {
            System.out.println("Plugin received a variable!");
            ModuleVariable variable = (ModuleVariable) evt.getNewValue();
            System.out.println("Variable name: " + variable.getVarName());
            System.out.println("Variable value: " + variable.getValue());
        }
    }
}
